apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
        - name: app
          image: nginx:latest  # 🔴 Bad: using latest tag
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 0  # 🔴 Bad: runs as root
          env:
            - name: API_KEY
              value: "12345-SECRET-KEY"  # 🔴 Hardcoded secret
